language: node_js
cache: yarn
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.1.0
  - export PATH="$HOME/.yarn/bin:$PATH"
node_js:
  - "8"
script:
  - yarn test
  - yarn deploy
  - ls -l build
  - sha256sum build.zip
deploy:
  provider: releases
  api_key: $GITHUB_OAUTH_TOKEN
  file: build.zip
  skip_cleanup: true
  on:
    tags: true
