language: node_js
cache: yarn
node_js:
  - "8"
script:
  - yarn test
  - yarn deploy
  - ls -l build
deploy:
  provider: releases
  api_key: $GITHUB_OAUTH_TOKEN
  file: build.zip
  skip_cleanup: true
  on:
    tags: true
