version: 2
jobs:
  build:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
      - run:
          name: install
          command: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run:
          name: test
          command: yarn test
      - run:
          name: deploy
          command: yarn deploy
      - run:
          name: collect artifacts
          command:
            - ls -l build/* build.zip
            - sha256sum build/* build.zip | tee SHA256SUMS.txt
            - mkdir dist
            - mv build.zip SHA256SUMS.txt
      - store_artifacts:
          path: dist
          destination: dist
