version: 2
jobs:
  build:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
      - run:
          name: install
          command: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
  test:
    docker:
      - image: circleci/node:latest
    steps:
      - run:
          name: test
          command: yarn test
  deploy:
    docker:
      - image: circleci/node:latest
    steps:
      - run:
          name: deploy
          command: yarn deploy
      - run:
          name: ls-stats
          command: ls -l build
      - store_artifacts:
          path: build.zip
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires: build
      - deploy:
          requires: test
